feat: add edx-sysadmin plugin app
mitodl/open-edx-plugins pull request #192
Opened 2023-09-13 12:52 UTC by arslanashraf7

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Migrations
  - [x] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [x] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
https://github.com/mitodl/edx-sysadmin/issues/76

**Note 1:**

I have also ported over the tests along with other components. The tests are currently not running because we will need to configure the test runup for the overall open-edx-plugins repo at some point. And these tests would run then.

**Note 2:**
For the initial pass, I ignored most of the warnings with `# noqa:` (No QA) to keep the scope of the PR narrow and try to not break any working functionality. Once we are done with this and everything works smoothly we should try and fix some of the pre-commit errors especially `PTH***` ones.

#### What's this PR do?
- Ports over the https://github.com/mitodl/edx-sysadmin to open-edx-plugins
- Adds the required pants configurations to support package creation of sysadmin
- Adds required plugin settings so that the sysadmin behaves as a plugin within the edX context
- Fixes lots of pre-commit warnings/errors. (There were so many pre-commit issues since this is an old code and was introduced to pre-commit for the first time. I have ignored most of the warnings and fixed the straightforward ones.)

#### How should this be manually tested?
- First of all, install sysadmin as mentioned in https://github.com/mitodl/edx-sysadmin
- Test the features mentioned in https://github.com/mitodl/edx-sysadmin
- Now, Setup up `open-edx-plugins` and generate package build e.g. using `./pants package ::`
- Install the package generated from this repo over the existing installation and see that:
    - There are no duplicate sysadmin packages
    - Everything(User creation, Course deletion, Course addition, Git logs, sysadmin commands such as `git_add_course`) works the same, especially the Git logs and course details.

**Note: (PRs you can take a look at for the steps to test the sysadmin overall, Follow instructions on those PRs)**
- https://github.com/mitodl/edx-sysadmin/pull/31
- https://github.com/mitodl/edx-sysadmin/pull/29
- https://github.com/mitodl/edx-sysadmin/pull/23

#### Where should the reviewer start?
- From an existing installation from the [old repo](https://github.com/mitodl/edx-sysadmin).

#### Screenshots

<img width="1035" alt="image" src="https://github.com/mitodl/open-edx-plugins/assets/34372316/412f2327-13ae-43a7-8403-70d9ddc7ce7b">

<img width="1357" alt="image" src="https://github.com/mitodl/open-edx-plugins/assets/34372316/342e59be-41fb-4118-923b-9e3678a4dc1a">

<img width="1277" alt="image" src="https://github.com/mitodl/open-edx-plugins/assets/34372316/4f837f65-ee62-4eee-95fe-b0afdcae0aaf">

<img width="1139" alt="image" src="https://github.com/mitodl/open-edx-plugins/assets/34372316/dbf7d002-fee6-4b5f-98d5-9d6dce90736a">

2023-09-13 18:09 UTC, blarghmatey commented on src/edx_sysadmin/requirements/base.in
These requirements should just be added to the top-level pyproject.toml as they won't be used at all. We don't need any of the contents of this requirements directory in the context of this repository.

2023-09-14 08:01 UTC, arslanashraf7 commented on src/edx_sysadmin/requirements/base.in
Thanks for pointing this out. I was kind of confused on this as well and thought i would decide about keeping or leaving it once the PR is ready for the feedback.

2023-09-25 09:18 UTC, asadali145 reviewed
I have tested sysadmin, it works fine. We should update the readme. Also, we should keep the import order. Overall, Looks great. An excellent effort to port the changes.

2023-09-25 09:18 UTC, asadali145 commented on src/edx_sysadmin/README.rst
> +edx-sysadmin
Readme needs some updates i.e. local installation etc

2023-09-25 09:18 UTC, asadali145 commented on src/edx_sysadmin/api/urls.py
> +from edx_sysadmin.api.views import (
We should keep an empty line between third-party and local imports as recommended.

2023-09-25 09:18 UTC, asadali145 commented on src/edx_sysadmin/api/views.py
> +
Import order is changed, We should keep the original https://github.com/mitodl/edx-sysadmin/blob/main/edx_sysadmin/api/views.py.

2023-09-25 09:18 UTC, asadali145 commented on src/edx_sysadmin/git_import.py
> +from xmodule.util.sandboxing import DEFAULT_PYTHON_LIB_FILENAME
I am not sure how the import order got changed as it was fine originally https://github.com/mitodl/edx-sysadmin/blob/main/edx_sysadmin/git_import.py

2023-09-25 09:18 UTC, asadali145 commented on src/edx_sysadmin/management/commands/git_add_course.py
> +from xmodule.modulestore.xml import XMLModuleStore
Import order.

2023-09-25 09:19 UTC, asadali145 commented
@blarghmatey This PR is ready for your review.

2023-09-25 13:20 UTC, blarghmatey approved these changes

2023-09-26 12:03 UTC, arslanashraf7 commented on src/edx_sysadmin/api/views.py
> +
That was done by pre-commit, I'll try to change it and see if pre-commit accepts.

2023-09-26 12:04 UTC, arslanashraf7 commented on src/edx_sysadmin/api/urls.py
> +from edx_sysadmin.api.views import (
That was done by pre-commit, I'll try to change it and see if pre-commit accepts.

2023-09-26 12:08 UTC, arslanashraf7 commented on src/edx_sysadmin/README.rst
> +edx-sysadmin
Good catch, We definitely need to update these.

2023-10-02 08:25 UTC, asadali145 requested changes
LGTM

2023-10-02 08:49 UTC, asadali145 approved these changes

2023-10-02 10:07 UTC, merged